---
- name: Deploy Cloud_movable from GitHub repo
  hosts: ansible_client
  
  vars:
    #remote_project_path: "/home/ubuntu/Cloud_Ansible"
    git_repo_url: "https://github.com/Nivethithachandru/Cloud_Ansible.git"

  tasks:

    - name: Ensure git is installed on remote host
      apt:
        name: git
        state: present
        update_cache: yes
      become: yes

    - name: Clone Cloud_Ansible repo from GitHub
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ project_path }}"
        version: main
        depth: 1
        force: yes

    - name: Disable Docker credential store
      copy:
        dest: "{{ ansible_env.HOME }}/.docker/config.json"
        content: |
          {
              "credsStore": ""
          }
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Build Docker image
      command: docker build -t movable .
      args:
        chdir: "{{ project_path }}"

    - name: Run Docker Compose (build + start)
      command: docker-compose up -d --build
      args:
        chdir: "{{ project_path }}"
